---
title: "mpls-violent-crimes.csv"
output: 
  rmdformats::html_docco:
    css: 'codebooks.css'
bibliography: '../../notes/epsy8264.bib'
csl: '../../notes/style/apa-single-spaced.csl'    
---


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
library(fontawesome)

## Global options
options(max.print = "75")
opts_chunk$set(
  echo = FALSE,
  prompt = FALSE,
  tidy = TRUE,
  comment = NA,
  message = FALSE,
  warning = FALSE
  )
opts_knit$set(width = 75)
```

The [mpls-violent-crime.csv](https://github.com/zief0002/epsy-8264/raw/master/data/mpls-violent-crime.csv) file contains data collected from the Minneapolis Police Department and reported by the [Star Tribune](http://www.startribune.com/a-deeper-look-at-minneapolis-crime-rates/493163741/) on  The two attributes in this file are:

- `year`: Year
- `crime_rate`: Violent crime rate per 100,000 people



### Preview

```{r}
options(dplyr.width = Inf, width = 85)
crime = readr::read_csv(file = "~/Documents/github/epsy-8264/data/mpls-violent-crime.csv")
head(crime)
```


<!-- ### References -->

<!-- <p style="padding-left: 50px; text-indent: -50px;"> -->

