---
title: "Assignment 02"
author: "Matrix Decomposition"
header-includes:
   - \usepackage{xcolor}
   - \usepackage{mathtools}
   - \definecolor{umn}{RGB}{153, 0, 85}
   - \definecolor{umn2}{rgb}{0.1843137, 0.4509804, 0.5372549}
output: 
  pdf_document:
    highlight: tango
    latex_engine: xelatex
    fig_width: 6
    fig_height: 6
mainfont: "Sabon"
sansfont: "Helvetica Neue UltraLight"
monofont: Inconsolata
urlcolor: "umn"
always_allow_html: yes
---


This goal of this assignment is to give you experience with matrix decomposition. Turn in a printed version of your responses to each of the questions on this assignment. 

In questions that ask you to "solve by hand", you can either use Equation Editor to input the matrices involved in your calculations, or include a picture of the actual hand calculations.

In addition, please adhere to the following guidelines for further formatting your assignment: 

- All graphics should be set to an appropriate aspect ratio and sized so that they do not take up more room than necessary. They should also have an appropriate caption.
- Any typed mathematics (equations, matrices, vectors, etc.) should be appropriately typeset within the document.
- Syntax or computer output should not be included in your assignment unless it is specifically asked for.

This assignment is worth 15 points. (Each question is worth 1 point unless otherwise noted.)


Use the matrix **A** throughout this assignment:

$$
\mathbf{A} = \begin{bmatrix}2 & 6\\-1 & 7\end{bmatrix}
$$


# Eigendecomposition 



Questions 1-5 in this section should be solved by hand. 

1. Find the eigenvalues of **A**.

2. Write the two specific characteristic equations.

3. Find the eigenvectors for **A**.


Compute and verify the following:

4. $\mathrm{tr}(\mathbf{A}) = \sum_{i=1}^n \lambda_i$

5. $\mathrm{det}(\mathbf{A}) = \prod_{i=1}^n \lambda_i$


Use R for Questions 6--8. Show the syntax you used. 

6. Verify that **P** is invertible.

7. Compute **D** using the eigenvectors you computed in Question 3.

8. Verify that $\mathbf{A}=\mathbf{P}\mathbf{D}\mathbf{P}^{-1}$

9. Use the equation for **A** given in Question 8 and the properties of matrix inverses to express $\mathbf{A}^{-1}$ as a function of **D** and **P**.

10. Verify the equation you produced in Question 9 using R. Show your syntax.


# LU Decomposition

11. Explain why we can we carry out LU (or LUP) decomposition on **A** by referring to the properties of **A**.  

12. Write out the system of equations, assuming **L** is a unit triangular matrix, that allow you to solve for the elements of **L** and **U**.

13. Give the **L** and **U** matrices.

14. Verify that the matrices given in Question 13 produce **A** using R. Show your syntax.

15. Use the LU decomposition to solve the following system of equations. Solve this by hand.

$$
\begin{split}
2x_1 + 6x_2 &= 24\\[0.5em]
-x_1 + 7x_2 &= 38
\end{split}
$$




