---
title: "Properties of Regression"
date: "`r Sys.Date()`"
header-includes:
   - \usepackage{amsthm}
   - \usepackage{xcolor}
   - \usepackage{xfrac}
   - \usepackage[framemethod=tikz]{mdframed}
   - \usepackage{graphicx}
   - \usepackage{rotating}
   - \usepackage{booktabs}
   - \usepackage{caption}
   - \definecolor{umn}{RGB}{153, 0, 85}
   - \definecolor{umn2}{rgb}{0.1843137, 0.4509804, 0.5372549}
   - \definecolor{myorange}{HTML}{EA6153}
output: 
  pdf_document:
    includes:
      before_body: notes.tex
    highlight: tango
    latex_engine: xelatex
    fig_width: 6
    fig_height: 6
mainfont: "Minion Pro"
sansfont: "ITC Slimbach Std Book"
monofont: "Source Code Pro"
urlcolor: "umn2"
always_allow_html: yes
bibliography: epsy8264.bib
csl: apa-single-spaced.csl
---

\frenchspacing

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(knitr)
library(kableExtra)
library(sm)
```

**P.1:** The OLS estimators $B_0$ and $B_1$ are correct (i.e., the equations for them produce the correct OLS estimates).

\vspace{4em}

**P.2:** The OLS line passes through the point $(\bar{x}, \bar{y})$.

\vspace{4em}

**P.3:** The sum and average value of the OLS residuals is zero.

\vspace{4em}

**P.4:** The OLS residuals are uncorrelated with $X$.

\vspace{4em}

**P.5:** The OLS residuals are uncorrelated with the fitted values.

\vspace{4em}

**P.6:** The OLS estimators are linear functions of the observations.

\vspace{4em}

**P.7:** The OLS estimators are unbiased estimators of the population coefficients.

\vspace{4em}

**P.8:** The sampling variances and a covariance for the OLS estimators are correct (i.e., the formulas are correct).

\vspace{4em}

**P.9:** The OLS estimators are the most efficient of all the linear, unbiased estimator

\vspace{4em}

**P.10:** The sampling distribution for the OLS estimators are normally distributed (or approximately normal).

\vspace{4em}

**P.11:** The OLS estimators are also the maximum-likelihood estimators of the population coefficients.
