# Calendar

Below is the tentative schedule for the class. The dates are subject to change at the instructor's discretion. 


<br />

<table class="table">

<thead>
<tr>
<th style="width:10%;text-align:center"></th>
<th style="width:10%;">Date</th>
<th style="width:70%;">Topic</th>
</tr>
</thead>



<tbody>


<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 08</td>
<td>Welcome to EPsy 8264</td>
</tr>


<!-- Unit 01: MATHEMATICS -->

<tr>
<td colspan="3"><b>Unit 01: Mathematics</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 10</td>
<td style="vertical-align:middle;" rowspan="2">A Bit of Linear Algebra</td>
</tr>



<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 15</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 17</td>
<td style="vertical-align:middle;" rowspan="2">Regression using Matrices</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 22</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 24</td>
<td style="vertical-align:middle;" rowspan="2">Matrix Decomposition</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Sept. 29</td>
</tr>


<!-- Unit 02: REGRESSION DIAGNOSTICS -->


<tr>
<td colspan="3"><b>Unit 02: Regression Diagnostics</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 01</td>
<td style="vertical-align:middle;" rowspan="2">Regression Diagnostics</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 06</td>
</tr>


   

<!-- Unit 03: HETEROSKEDASTICITY-->

<tr>
<td colspan="3"><b>Unit 03: Dealing with Heteroskedasticity</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 08</td>
<td style="vertical-align:middle;">Variance Stabilizing  Transformations</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 13</td>
<td style="vertical-align:middle;">Weighted Least Squares (WLS) and Sandwich Estimation</td>
</tr>


<!-- Unit 04: COLLINEARITY-->


<tr>
<td colspan="3"><b>Unit 04: Dealing with Collinearity</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 15</td>
<td style="vertical-align:middle;">Collinearity Diagnostics</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 20</td>
<td style="vertical-align:middle;" rowspan="2">Variable reduction</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 22</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 27</td>
<td style="vertical-align:middle;" rowspan="2">Biased Estimation and Shrinkage</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Oct. 29</td>
</tr>


<!-- Unit 05: MODEL SELECTION -->


<tr>
<td colspan="3"><b>Unit 05: Model Selection</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 03</td>
<td style="vertical-align:middle;">NO CLASS&mdash; Election Day</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 05</td>
<td style="vertical-align:middle;">Traditional Methods of Model Selection</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 12</td>
<td style="vertical-align:middle;" rowspan="2">Cross-Validation</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 17</td>
</tr>


<!-- Unit 06: NONLINEARITY -->

<tr>
<td colspan="3"><b>Unit 06: Piecewise Modeling</b></td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 24</td>
<td style="vertical-align:middle;">Piecewise Regression</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Nov. 26</td>
<td style="vertical-align:middle;">NO CLASS&mdash;Thanksgiving Break</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Dec. 01</td>
<td style="vertical-align:middle;">Piecewise Regression</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Dec. 03</td>
<td style="vertical-align:middle;" rowspan="3">Spline Models</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Dec. 08</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Dec. 10</td>
</tr>

<tr>
<td align="center" style="vertical-align:middle;">&nbsp;</td>
<td>Dec. 15</td>
<td style="vertical-align:middle;">*TBA*</td>
</tr>

</tbody>
</table>

