# Materials


### Welcome to EPsy 8264 

**Prior to class:**

- Download and read through the [course syllabus](https://github.com/zief0002/epsy-8264/raw/master/syllabus/f20-epsy-8264-syllabus.pdf)


**After class:**

- If you will be using your computer for statistical computing (rather than the RStudio server), install (or update) R and RStudio onto your personal computer. See [R and RStudio Installation and Setup](https://zief0002.github.io/toolkit/r-and-rstudio-installation-and-setup.html#r-and-rstudio-installation-and-setup) for help.

---


### A Bit of Linear Algebra (Sept. 10)

In this unit we will learn some of the basic linear/matrix algebra that is useful for regression analyses. 

**Prior to Class:**

- Read Fox (Sections 1.1&ndash;1.4)


**In Class**

- [Introduction to Matrix Algebra](https://zief0002.github.io/epsy-8264/misc/01-introduction-to-matrix-algebra.html) [Course Notes]


**Additional Resources**


- Burrill, G., Burrill, J., Landwehr, J. & Witmer, J. (1998). [Advanced modeling and matrices](http://www.amstat.org/asa/files/pdfs/ddmseries/AdvancedModelingandMatrices--TeachersEdition.pdf) Orangeburg, NY: Dale Seymour Publications. *(This is a module from Data-Driven Mathematics written for secondary school students and teachers)*
- Irizarry, R., & Love, M. (2018). [Biomedical data science](http://genomicsclass.github.io/book/) PH525x series. *(Chapter 4 addresses matrix algebra)*
- Namboodiri, N. K. (1984). [Matrix algebra: An introduction](https://primo.lib.umn.edu/permalink/f/dkvf4l/TN_cdi_proquest_ebookcentral_EBC3032594). Thousand Oaks, CA: Sage.
- Savov, I. (2017). No bullshit guide to linear algebra. Minireference Co.


<br />

---


### Some Vector Geometry (Sept. 15)

In this unit we will look at some of the geometric ideas underlying vectors that are useful for regression analyses. 

**Prior to Class:**

- Watch 3Blue1Brown. (2016). [Vectors, what even are they?](https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab&index=1&ab_channel=3Blue1Brown). From the series of YouTube videos *Essence of linear algebra.*


**In Class**

- [Some Vector Geometry](https://github.com/zief0002/epsy-8264/raw/master/notes/01-some-vector-geometry.pdf) [Course Notes]


**Additional Resources**

- The remainder of the 3Blue1Brown videos (2016). [Essence of linear algebra](https://www.youtube.com/watch?v=kjBOesZCoqc&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab).

<br />

---


### Regression using Matrices (Sept. 17; 22)

In this unit we will learn some of the basic linear/matrix algebra that is useful for regression analyses. 

**Prior to Class:**

- Read Fox (Sections 4.1&ndash;4.6)


**In Class**

- [Regression Using Matrices](https://zief0002.github.io/epsy-8264/misc/02-regression-using-matrices.html) [Course Notes]

<!-- **Notes for Class** -->

<!-- - [Introduction to Matrix Algebra](http://zief0002.github.io/epsy-8264/misc/05-introduction-to-matrix-algebra.html) -->


**Additional Resources**

- 3Blue1Brown. (2016). [Essence of linear algebra](https://www.youtube.com/watch?v=kjBOesZCoqc&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab). *(These YouTube videos will help explain some of the concepts explained in Fox Sections 1.3; 1.4)*
- Gruber, M. H. J. (2014). [Matrix algebra for linear models](https://www.mobt3ath.com/uplode/book/book-33745.pdf). Wiley.

<br />

---

### Matrix Decomposition (Sept. 24; 29)

**Prior to Class:**

- Read Fox (Sections 1.6)


**In Class**

- [Introduction to Matrix Decomposition](https://zief0002.github.io/epsy-8264/misc/03-matrix-decomposition.html) [Course Notes]
- [Eigendecomposition](https://zief0002.github.io/epsy-8264/misc/04-eigen-decomposition.html) [Course Notes]


**Additional Resources**

- 3Blue1Brown. (2016). [Essence of linear algebra](https://www.youtube.com/watch?v=kjBOesZCoqc&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab). *(Especially the video on eigenvalues and eigenvectors)*

<br />

---



### Regression Diagnostics (Oct. 01; 06)

**Prior to Class:**

- Read Fox, J. (1991). [Outlying and influential data](https://primo.lib.umn.edu/permalink/f/1q7ssba/UMN_ALMA21512855700001701). In *Regression Diagnostics* (pp. 21--40). Sage. doi: https://dx-doi-org.ezp1.lib.umn.edu/10.4135/9781412985604.n4 [Online Access via UMN Library]


**In Class**

- [Regression Diagnostics](https://github.com/zief0002/epsy-8264/raw/master/notes/07-regression-diagnostics.pdf) [Course Notes]


**Additional Resources**

- Kim, B. (2015). [Understanding diagnostic plots for linear regression analysis](https://data.library.virginia.edu/diagnostic-plots/). University of Virginia Library.
- Cook, R. D. (1998). [Regression graphics: Ideas for studying regressions through graphics](http://www.stat.umn.edu/RegGraph/). Wiley.
<br />

---


### Variance Stabilizing Transformations (Oct. 08)

**Prior to Class:**

- Read Osborne, J. W. (2009). [Notes on the use of data transformations](http://PAREonline.net/getvn.asp?v=8&n=6). *Practical Assessment, Research & Evaluation, 8*(6). 



**In Class**

- First part of [Dealing with Heteroskedasticity](https://zief0002.github.io/epsy-8264/misc/08-heteroskedasticity-and-wls.html) [Course Notes]
- [Script File](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/08-heteroskedasticity-and-wls-estimation.R) [R script]


**Additional Resources**

- Kaufman, R. L. (2013). [Heteroskedasticity in regression: Detection and correction](https://primo.lib.umn.edu/permalink/f/1q7ssba/UMN_ALMA21449350120001701). Sage. https://dx-doi-org.ezp1.lib.umn.edu/10.4135/9781452270128.n4 [Online Access via UMN Library]

<br />

---


### Weighted Least Squares (WLS) and Sandwich Estimation (Oct. 13)

**Prior to Class:**

- Read Kaufman, R. L. (2013). Heteroskedasticity-Consistent (Robust) Standard Errors. In [Heteroskedasticity in regression: Detection and correction](https://primo.lib.umn.edu/permalink/f/1q7ssba/UMN_ALMA21449350120001701) (pp. 43--50). Sage. https://dx-doi-org.ezp1.lib.umn.edu/10.4135/9781452270128.n4 [Online Access via UMN Library]



**In Class**

- Second part of [Dealing with Heteroskedasticity](https://zief0002.github.io/epsy-8264/misc/08-heteroskedasticity-and-wls.html) [Course Notes]


**Additional Resources**

- Shin, H.-C. (1998). Weighted least squares estimation with sampling weights. *Journal of Econometrics, 8*(2), 251--271.
- Solon, G., Haider, S. J., & Woolridge, J. (2013). [What are we weighting for?](https://www.nber.org/papers/w18859) (Working Paper No. 18859; NBER Working Paper Series). National Bureau of Economic Research.


<br />

---


### Collinearity Diagnostics (Oct. 15)

**Prior to Class:**

- Nothing

<!-- - Read Kaufman, R. L. (2013). Heteroskedasticity-Consistent (Robust) Standard Errors. In [Heteroskedasticity in regression: Detection and correction](https://primo.lib.umn.edu/permalink/f/1q7ssba/UMN_ALMA21449350120001701) (pp. 43--50). Sage. https://dx-doi-org.ezp1.lib.umn.edu/10.4135/9781452270128.n4 [Online Access via UMN Library] -->



**In Class**

- [Collinearity Diagnostics](https://zief0002.github.io/epsy-8264/misc/09-collinearity-diagnostics.html) [Course Notes]
- [Script File](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/09-collinearity-diagnostics.R) [R script]


**Additional Resources**

- Cook, D. (2019). [How to use a tour to check if your model suffers from multicollinearity.](http://dicook.org/2019/09/13/touring-to-check-for-multicollinearity/) Personal blog.


<br />

---


### Principal Components Analysis via Eigendecomposition (Oct. 20)

**Prior to Class:**

- Nothing

<!-- - Read Kaufman, R. L. (2013). Heteroskedasticity-Consistent (Robust) Standard Errors. In [Heteroskedasticity in regression: Detection and correction](https://primo.lib.umn.edu/permalink/f/1q7ssba/UMN_ALMA21449350120001701) (pp. 43--50). Sage. https://dx-doi-org.ezp1.lib.umn.edu/10.4135/9781452270128.n4 [Online Access via UMN Library] -->



**In Class**

- First part of [Principal Components Analysis](https://zief0002.github.io/epsy-8264/misc/10-principal-components-analysis.html) [Course Notes] <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Updated 10-14-2020]*</span>
- [Script File](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/10-principal-components-analysis.R) [R script]


**Additional Resources**

- Wilke, C. O. (2020). [PCA tidyverse style.](https://clauswilke.com/blog/2020/09/07/pca-tidyverse-style/) Personal blog.


<br />

---


### Principal Components Analysis via Singular Value Decomposition (Oct. 22)

**Prior to Class:**

- Gundersen, G. (2018). [Singular value decomposition as simply as possible](http://gregorygundersen.com/blog/2018/12/10/svd/).



**In Class**

- Second part of [Principal Components Analysis](https://zief0002.github.io/epsy-8264/misc/10-principal-components-analysis.html) [Course Notes]
- [Script File](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/10-principal-components-analysis.R) [R script]


**Additional Resources**

- Wang, Z. (2019). [PCA and SVD explained with numpy](https://towardsdatascience.com/pca-and-svd-explained-with-numpy-5d13b0d2a4d8).
- Wikipdeia. (2020). [Singular value decomposition](https://en.wikipedia.org/wiki/Singular_value_decomposition).


<br />

---


### Biased Estimation and Shrinkage (Oct. 27--29)

**Prior to Class:**

- Fortmann-Roe, S. (2012). [Understanding the bias-variance tradeoff](http://scott.fortmann-roe.com/docs/BiasVariance.html).


**In Class**

- [Shrinkage Methods: Ridge Regression](https://zief0002.github.io/epsy-8264/misc/11-shrinkage-methods-ridge-regression.html) [Course Notes]
- [Script File 1](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/11-shrinkage-methods-ridge-regression.R) [R script]
- [Script File 2](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/11-shrinkage-methods-ridge-regression-02.R) [R script]


**Additional Resources**

- Cross-Validated. (2014). [Why is ridge regression called "ridge", why is it needed, and what happens when $\lambda$ goes to infinity?](https://stats.stackexchange.com/questions/151304/why-is-ridge-regression-called-ridge-why-is-it-needed-and-what-happens-when).
- James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2013). [An introduction to statistical learning: with applications in R](https://www-bcf.usc.edu/~gareth/ISL/). New York: Springer.
- [Statistical Learning MOOC](https://lagunita.stanford.edu/courses/HumanitiesSciences/StatLearning/Winter2016/about) taught by Hastie and Tibshirani


<br />

---


### Model Selection (Nov. 05--10)

**Prior to Class:**

- Heinze, G., Wallisch, C., &amp; Dunkler, D. (2018). [Variable selection --- A review and recommendations for the practicing statistician.](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5969114/) *Biometrical Journal. Biometrische Zeitschrift, 60*(3), 431--449. https://doi.org/10.1002/bimj.201700067


**In Class**

- [Model Selection](https://github.com/zief0002/epsy-8264/raw/master/notes/12-model-selection.pdf) [Course Notes]
- [Script File 1](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/12-model-selection.R) [R script]


**Additional Resources**

- [olsrr Vignette](https://cran.r-project.org/web/packages/olsrr/vignettes/intro.html)
- Williams, B., Hansen, G., Baraban, A., &amp; Santoni, A. (2015). [A practical approach to variable selection---A comparison of various techniques.](https://www.casact.org/pubs/forum/15sumforum/Williams-Hansen-Baraban-Santoni.pdf) *Casualty Actuarial Society E-Forum, Summer*, 1--20.


<br />

---


### Cross-Validation (Nov. 12--17)

**Prior to Class:**

- Feick, L. (2019). [Evaluating model performance by building cross-validation from scratch.](https://www.statworx.com/de/blog/evaluating-model-performance-by-building-cross-validation-from-scratch/) STATWORX Blog.


**In Class**

- [Cross-Validation](https://zief0002.github.io/epsy-8264/misc/13-cross-validation.html) [Course Notes]
- [Script File](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/13-cross-validation.R) [R script]
- [Shrinkage Methods: LASSO and Elastic Net](https://zief0002.github.io/epsy-8264/misc/14-shrinkage-methods-lasso-and-elastic-net.html) [Course Notes]
- [Script File](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/14-shrinkage-methods-lasso-and-elastic-net.R) [R script]


**Additional Resources**

- Brownlee, J. (2018). [A gentle introduction to k-fold cross-validation.](https://machinelearningmastery.com/k-fold-cross-validation/) Machine Learning Mastery.
- Bryan, J. (n.d.). [purrr tutorial.](https://jennybc.github.io/purrr-tutorial/)
- Hastie, T., &amp; Qian, J. (2014). [Glmnet vignette.](https://web.stanford.edu/~hastie/glmnet/glmnet_alpha.html)
- log0. (2018). [Differences between L1 and L2 as loss function and regularization.](http://www.chioka.in/differences-between-l1-and-l2-as-loss-function-and-regularization/)
- McCammon, J. (2014). [Lasso and ridge regression in R.](https://jamesmccammon.com/2014/04/20/lasso-and-ridge-regression-in-r/)
- Zou, H., &amp; Hastie, T. (2005). [Regularization and variable selection via the elastic net.](https://web.stanford.edu/~hastie/Papers/B67.2%20(2005)%20301-320%20Zou%20&%20Hastie.pdf) *Journal of the Royal Statistical Society (Series B), 67*, Part 2, 301–-320.



<br />


### Piecewise Regression (Nov. 19-- Dec. 03)

**Prior to Class:**

- Nothing.


**In Class**

- [Piecewise Regression](https://zief0002.github.io/epsy-8264/misc/15-piecewise-regression.html) [Course Notes]
- [Script File](https://raw.githubusercontent.com/zief0002/epsy-8264/master/scripts/15-piecewise-regression.R) [R script]


**Additional Resources**

- Berk, R. (2016). Splines, smoothers, and kernels.  *Statistical learning from a regression perspective* (2nd ed., pp. 55&ndash;127). Springer.
- Fox, J. (2016). Nonlinear regression. *Applied regression analysis and generalized linear models* (3rd ed., pp.502&ndash;527). Thosand Oaks, CA: Sage.
- James, G., Witten, D., Hastie, T., & Tibshirani, R. (2013). Moving beyond linearity. *[An introduction to statistical learning: with applications in R](https://www-bcf.usc.edu/~gareth/ISL/)* (pp. 265&ndash;301). New York: Springer.
- [Statistical Learning MOOC](https://lagunita.stanford.edu/courses/HumanitiesSciences/StatLearning/Winter2016/about) taught by Hastie and Tibshirani


<br />

---

